spring:
  application:
    name: userClient
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.250/mysql
    username: root
    password: ps123456
server:
  port: 80
  port: 8881
eureka:
  instance:
    hostname: localhost
@@ -17,7 +9,15 @@ eureka:
    #是否注册到注册中心
    registerWithEureka: true
    #是否抓取注册中心的注册信息
    fetchRegistry: true
    fetchRegistry: false
    serviceUrl:
      #微服务和客户端用来注册和发现的地址
    #微服务和客户端用来注册和发现的地址
      defaultZone: http://192.168.174.129:8761/eureka/
spring:
  application:
    name: userService
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.250/school
    username: root
    password: ps123456
