server:
  port: 8881
eureka:
  instance:
    hostname: localhost
    #注册到注册中心的微服务都是IP地址
    preferIpAddress: true
  client:
    #是否注册到注册中心
    registerWithEureka: true
    #是否抓取注册中心的注册信息
    fetchRegistry: false
    serviceUrl:
    #微服务和客户端用来注册和发现的地址
      defaultZone: http://192.168.174.130:8761/eureka/
spring:
  application:
    name: userService
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.250/school
    username: root
    password: ps123456
